tword = [{text: 'Suns', size: 100},
{text: 'Grizzlies', size: 73},
{text: 'Heat', size: 67},
{text: 'Warriors', size: 65},
{text: 'Mavericks', size: 62},
{text: 'Celtics', size: 59},
{text: '76ers', size: 57},
{text: 'Jazz', size: 57},
{text: 'Bucks', size: 54},
{text: 'Nuggets', size: 52},
{text: 'Raptors', size: 50},
{text: 'Bulls', size: 47},
{text: 'Timberwolves', size: 45},
{text: 'Nets', size: 43},
{text: 'Cavaliers', size: 43},
{text: 'Hornets', size: 41},
{text: 'Hawks', size: 40},
{text: 'Clippers', size: 40},
{text: 'Knicks', size: 31},
{text: 'Wizards', size: 30},
{text: 'Pelicans', size: 29},
{text: 'Spurs', size: 28},
{text: 'Lakers', size: 25},
{text: 'Kings', size: 23},
{text: 'Trail Blazers', size: 22},
{text: 'Pacers', size: 20},
{text: 'Magic', size: 20},
{text: 'Thunder', size: 20},
{text: 'Pistons', size: 20},
{text: 'Rockets', size: 20}
];
